### ISSUE TITLE
WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。

### ISSUE THREAD

**Issue by KelaLeaf** [avilliai/wReply#1]
安装完依赖后运行提示：
C:\Program Files\python\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
已读取字典
已读取模糊匹配字典
已读取信任用户
2023-02-02 16:11:34 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
此时程序停止运行

执行pip install uvicorn命令后：
PS E:\Program Files\mirai\wReply-master> python main.py
C:\Program Files\python\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
已读取字典
已读取模糊匹配字典
已读取信任用户
Traceback (most recent call last):
  File "main.py", line 609, in <module>
    bot.run()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 257, in run
    if not asgi_serve(
  File "C:\Program Files\python\lib\site-packages\mirai\asgi.py", line 205, in asgi_serve
    run(app, host=host, port=port, debug=True, **kwargs)
TypeError: run() got an unexpected keyword argument 'debug'

执行pip install hypercorn命令后：
PS E:\Program Files\mirai\wReply-master> python main.py
C:\Program Files\python\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
已读取字典
已读取模糊匹配字典
已读取信任用户
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-2' coro=<Lifespan.handle_lifespan() done, defined at C:\Program Files\python\lib\site-packages\hypercorn\asyncio\lifespan.py:31> exception=LifespanFailureError('Lifespan failure in startup. \'Traceback (most recent call last):\n  File "C:\\Program Files\\python\\lib\\site-packages\\mirai\\adapters\\websocket.py", line 141, in _receiver\n    response = json.loads(await self.connection.recv())\n  File "C:\\Program Files\\python\\lib\\site-packages\\websockets\\legacy\\protocol.py", line 568, in recv\n    await self.ensure_open()\n  File "C:\\Program Files\\python\\lib\\site-packages\\websockets\\legacy\\protocol.py", line 944, in ensure_open\n    raise self.connection_closed_exc()\nwebsockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Program Files\\python\\lib\\asyncio\\runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "C:\\Program Files\\python\\lib\\asyncio\\base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "C:\\Program Files\\python\\lib\\asyncio\\windows_events.py", line 316, in run_forever\n    super().run_forever()\n  File "C:\\Program Files\\python\\lib\\asyncio\\base_events.py", line 570, in run_forever\n    self._run_once()\n  File "C:\\Program Files\\python\\lib\\asyncio\\base_events.py", line 1851, in _run_once\n    handle._run()\n  File "C:\\Program Files\\python\\lib\\asyncio\\events.py", line 81, in _run\n    self._context.run(self._callback, *self._args)\n  File "C:\\Program Files\\python\\lib\\site-packages\\mirai\\adapters\\base.py", line 35, in wrapped\n    return await func(self, *args, **kwargs)\n  File "C:\\Program Files\\python\\lib\\site-packages\\mirai\\adapters\\websocket.py", line 151, in _receiver\n    raise SystemExit()\nSystemExit\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Program Files\\python\\lib\\site-packages\\starlette\\routing.py", line 671, in lifespan\n    async with self.lifespan_context(app):\n  File "C:\\Program Files\\python\\lib\\site-packages\\starlette\\routing.py", line 566, in __aenter__\n    await self._router.startup()\n  File "C:\\Program Files\\python\\lib\\site-packages\\starlette\\routing.py", line 648, in startup\n    await handler()\n  File "C:\\Program Files\\python\\lib\\site-packages\\mirai\\bot.py", line 228, in startup\n    await asyncio.gather(*coros)\nasyncio.exceptions.CancelledError\n\'') created at C:\Program Files\python\lib\site-packages\hypercorn\asyncio\run.py:76>
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\websocket.py", line 141, in _receiver
    response = json.loads(await self.connection.recv())
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 568, in recv
    await self.ensure_open()
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 1851, in _run_once
    handle._run()
  File "C:\Program Files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\websocket.py", line 151, in _receiver
    raise SystemExit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 228, in startup
    await asyncio.gather(*coros)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\hypercorn\asyncio\lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "C:\Program Files\python\lib\site-packages\hypercorn\app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 236, in __call__
    await self._asgi(scope, recv, send)
  File "C:\Program Files\python\lib\site-packages\mirai\asgi.py", line 165, in __call__
    await self.app(scope, recv, send)
  File "C:\Program Files\python\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Program Files\python\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Program Files\python\lib\site-packages\starlette\middleware\exceptions.py", line 55, in __call__
    await self.app(scope, receive, send)
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 695, in __call__
    await self.lifespan(scope, receive, send)
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 680, in lifespan
    await send({"type": "lifespan.startup.failed", "message": exc_text})
  File "C:\Program Files\python\lib\site-packages\hypercorn\asyncio\lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\websocket.py", line 141, in _receiver
    response = json.loads(await self.connection.recv())
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 568, in recv
    await self.ensure_open()
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 1851, in _run_once
    handle._run()
  File "C:\Program Files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\websocket.py", line 151, in _receiver
    raise SystemExit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Program Files\python\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 228, in startup
    await asyncio.gather(*coros)
asyncio.exceptions.CancelledError
'
目前本人是py38版本的，出现了以上报错。

使用py39时也出现过同样的问题，使用hypercorn能运行，使用uvicorn会报错。
后来运行了一段时间程序不能启动了，报错内容由于我现在换成了py38所以没法提供了。

换成py38也是无赖，宝塔是用的py38，py39的话宝塔无法运行。

**Comment by avilliai** [comment]
“2023-02-02 16:11:34 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 uvicorn 或 hypercorn。
在命令行键入：
pip install uvicorn
或者
pip install hypercorn”

还有第一行的警告可以忽略，安装了这两个东西的话卸载掉，至于不能运行的问题，推测是配置有写错的地方。
这是main.py中的代码。
if __name__ == '__main__':

    bot = Mirai(3377428814, adapter=WebSocketAdapter(
        verify_key='1234567890', host='localhost', port=23456
    ))

如果你使用了项目中带有的setting.yml替换了mcl根目录\config\net.mamoe.mirai-api-http\setting.yml，以上代码只需修改3377428814为你bot的qq(运行bot.py时需要确保bot已在mcl登录)

**Comment by KelaLeaf** [comment]
> “2023-02-02 16：11：34 - 警告未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 uvicorn 或 hypercorn。 在命令行键入： pip install uvicorn 或者 pip install hypercorn”
> 
> 还有第一行的警告可以忽略，安装了这两个东西的话卸载掉，至于不能运行的问题，推测是配置有写错的地方。 这是 main.py 中的代码。如果**名称** == '**main**'：
> 
> ```
> bot = Mirai(3377428814, adapter=WebSocketAdapter(
>     verify_key='1234567890', host='localhost', port=23456
> ))
> ```
> 
> 如果你使用了项目中带有的setting.yml替换了mcl根目录\config\net.mamoe.mirai-api-http\setting.yml，以上代码只需修改3377428814为你bot的qq（运行 bot.py 时需要确保bot已在mcl登录）

卸载这两个模块了，刚刚配置也修改了
出现了新的报错：
PS E:\Program Files\mirai\wReply> python main.py
C:\Program Files\python\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
已读取字典
已读取模糊匹配字典
已读取信任用户
2023-02-02 17:07:34 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-02-02 17:07:44 - ERROR
Traceback (most recent call last):
  File "main.py", line 631, in <module>
    bot.run()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 276, in run
    asyncio.run(self._run())
  File "C:\Program Files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 240, in _run
    await self.startup()
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "C:\Program Files\python\lib\site-packages\mirai\bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\Program Files\python\lib\asyncio\tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

**Comment by KelaLeaf** [comment]
卸载这两个模块了，刚刚配置也修改了

`   bot = Mirai(3064977689, adapter=WebSocketAdapter(
        verify_key='5922880', host='127.0.0.1', port=1660
    ))

verifyKey: 5922880 # 你可以自己设定, 这里作为示范, 请保持和 config.yaml 中 verify_key 项一致
singleMode: false
cacheSize: 4096 # 可选, 缓存大小, 默认4096. 缓存过小会导致引用回复与撤回消息失败
adapterSettings:
  http:
    host: 127.0.0.1
    port: 1660 # 端口
    cors: [*]

  ws:
    host: 127.0.0.1
    port: 1660 # 端口
    reservedSyncId: -1 # 确保为 -1, 否则 WebsocketAdapter(Experimental) 没法正常工作.`

依旧：
PS E:\Program Files\mirai\wReply> python main.py
C:\Program Files\python\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
已读取字典
已读取模糊匹配字典
已读取信任用户
2023-02-02 17:21:40 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
PS E:\Program Files\mirai\wReply>

**Comment by avilliai** [comment]
asyncio.exceptions.CancelledError报错问题我在yiri-mirai的群里问过了，排除配置文件错误的可能性之后，可能就是yiri-mirai的问题了(之前有用linux服务器的朋友反馈了差不多的报错)，而yiri-mirai已经停止维护。随后我会尝试使用graia ariadne替换yirimirai。

**Comment by KelaLeaf** [comment]
谢谢作者大大的回复，我会持续关注您的项目，我感觉它非常的棒。
但是我还有一点建议希望您能够采纳;
1.群聊内需要at机器人或者带有自定义固定聊天前缀时机器人会绝对回复（并不与回复概率相矛盾，没有at机器人或者固定前缀时依旧概率回复，设置概率为零则为只有at或者带有固定前缀时机器人才回复）
2.添加延时回复的功能，延时可以随机或者自定义固定延时（模仿真人聊天，应该可以降低封号概率）
